buildVariable: true
familyName: Noto Kufi Arabic
glyphData:
- GlyphData.xml
googleFonts: true
includeSubsets:
- from: Noto Sans
  name: GF_Latin_Core
recipeProvider: noto
sources:
- NotoKufiArabic.glyphspackage
